language: erlang
sudo: false

os: linux
opt_release: 20.2

matrix:
  include:
    - os: linux
      otp_release: 20.2
    - os: linux
      otp_release: 20.0

cache:
  directories:
    - $HOME/.cache/rebar3

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

script:
  - rebar3 dialyzer
